---
stages:
- name: esa build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      # your script here
      echo test
- name: MyStage
  inputs:
  - type: job
    stage: esa build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: esa deploy
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: eric.samuelsson@se.ibm.com
      space: dev
      application: deploytest
    script: |
      #!/bin/bash
      echo YYY