---
stages:
- name: esa build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      # your script here
      echo test
- name: esa deploy
  inputs:
  - type: job
    stage: esa build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      echo YYY
- name: esa deploy2
  inputs:
  - type: job
    stage: esa build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      echo YYY
